services:
  - type: web
    name: crypto-pulse-ai
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_API_KEY_HELPER
        sync: false
      - key: GROQ_MODEL_HELPER
        value: llama-3.1-8b-instant
      - key: PORT
        value: 3000
